import '@/styles/app.scss';
import type { Metadata } from 'next';
import Navbar from '@/app/components/Navbar/Navbar';
import React, { Suspense, useContext } from 'react';
import { i18n, Locale } from 'i18n.config';
import Footer from '@/app/components/Footer/Footer';
import { getDictionary } from '@/app/[lang]/dictionaries';
import NavbarDictionaryProvider from '@/app/utils/contexts';
import { Inter } from 'next/font/google';
import { PUBLIC_URL } from '@/constants/constants';

const inter = Inter({
  subsets: ['latin'],
});
export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NODE_ENV === 'development'
      ? 'http://localhost:3000'
      : PUBLIC_URL,
  ),
  title: 'Boat Excursion Niko',
  description: 'Generated by create next app',
  twitter: {
    card: 'summary_large_image',
  },
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const { navigation, footer } = await getDictionary(params.lang);
  return (
    <html lang={params.lang}>
      <body>
        <NavbarDictionaryProvider dictionary={navigation}>
          <Navbar lang={params.lang} />
        </NavbarDictionaryProvider>

        <main>{children}</main>

        <NavbarDictionaryProvider dictionary={navigation}>
          <Footer lang={params.lang} footerDictionary={footer} />
        </NavbarDictionaryProvider>
      </body>
    </html>
  );
}
