import '@/styles/app.scss';

import React from 'react';
import AdminNavbar from '@/app/components/Navbar/AdminNavbar';
import { useDetectWindowSize } from '@/hooks/useDetectWindowSize';
import { SessionProvider } from 'next-auth/react';
import { getServerSession } from 'next-auth';
import { getTokens, Tokens } from 'next-firebase-auth-edge';
import { cookies } from 'next/headers';
import { authConfig } from '@/app/utils/authServerConfig';
import { User } from '@/app/utils/AuthProvider';
import { filterStandardClaims } from 'next-firebase-auth-edge/lib/auth/claims';
import { redirect } from 'next/navigation';

export const metadata = {
  title: 'Boat Excursion Niko | Admin',
  description: 'Generated by Next.js',
};

const toUser = ({ decodedToken }: Tokens): User => {
  const {
    uid,
    email,
    picture: photoURL,
    email_verified: emailVerified,
    phone_number: phoneNumber,
    name: displayName,
    source_sign_in_provider: signInProvider,
  } = decodedToken;

  const customClaims = filterStandardClaims(decodedToken);

  return {
    uid,
    email: email ?? null,
    displayName: displayName ?? null,
    photoURL: photoURL ?? null,
    phoneNumber: phoneNumber ?? null,
    emailVerified: emailVerified ?? false,
    providerId: signInProvider,
    customClaims,
  };
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const tokens = await getTokens(cookies(), authConfig);
  const user = tokens ? toUser(tokens) : null;

  if (!user) {
    redirect('/admin');
    return null;
  }

  return (
    <html lang="hr">
      <body>
        <AdminNavbar />
        {children}
      </body>
    </html>
  );
}
